[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true

[tool.pydocstyle]
convention = "google"

[tool.pylint.master]
load-plugins = "pylint_flask_sqlalchemy"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "100"

[tool.pytest.ini_options]
addopts = "--cov=supermarket --cov-report=term"
python_classes = [
  "*Test",
  "Test*",
]
